## Gene panel statistics

In [1]:
import pandas as pd
import numpy as np
import os
import anndata as ad
import squidpy as sq
import scanpy as sc
from pathlib import Path
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
print(os.getcwd())
this_path = os.getcwd()

C:\Users\Chenxi Zhou\Desktop\Neural Crest\SingleCrest\merscope\result\analysis\2025MAY\Tutorial_Github\tutorial

In [2]:
adata = ad.read_h5ad("MER02_R1_filtered_stage22_subset.h5ad")
adata.X = adata.layers["raw_counts"]

path_save = str(os.getcwd()) + "//gene_panel_QC//"
Path.mkdir(Path(path_save), parents=True, exist_ok = True)

## statistics of gene expression

In [4]:

## statistics of gene expression matrix
adata.X = adata.layers["raw_counts"]
stat = sc.pp.calculate_qc_metrics(adata,percent_top=(1,5,10,15))
stat[0].to_csv(path_save + "cell_stat.csv")  
stat[1].to_csv(path_save + "gene_stat.csv")

stat[1]

,n_cells_by_counts,mean_counts,log1p_mean_counts,pct_dropout_by_counts,total_counts,log1p_total_counts
ACTC1.L,3350,43.095860,3.786366,49.744974,287277.0,12.568206
CD44.L,2294,1.222022,0.798418,65.586559,8146.0,9.005405
CDH1.S,4113,9.354486,2.337420,38.298830,62357.0,11.040648
CDX4.L,990,0.292529,0.256601,85.148515,1950.0,7.576097
CHRD.1.S,3311,4.406841,1.687665,50.330033,29376.0,10.287968
DLX2.L,1201,1.174017,0.776577,81.983198,7826.0,8.965335
DLX3.L,4173,2.525352,1.259980,37.398740,16834.0,9.731215
EGR2.L,1522,0.678818,0.518090,77.167717,4525.0,8.417594
ELAVL3.L,1460,1.717072,0.999555,78.097810,11446.0,9.345483
EPHA2.L,4778,6.428143,2.005276,28.322832,42850.0,10.665484
EPHA4.L,4687,7.243474,2.109422,29.687969,48285.0,10.784897
EYA1.L,3287,1.412241,0.880556,50.690069,9414.0,9.150060
FOXC2.L,3741,4.964447,1.785816,43.879388,33093.0,10.407107
GATA2.L,4568,6.893489,2.066038,31.473147,45952.0,10.735374
GBX2.2.L,2158,0.755176,0.562569,67.626763,5034.0,8.524169
HNF1B.L,2762,1.477198,0.907128,58.565857,9847.0,9.195024
HOXA3.S,3958,1.734774,1.006049,40.624062,11564.0,9.355739
HOXC10.L,1326,0.258176,0.229663,80.108011,1721.0,7.451241
HOXD3.L,1578,0.533303,0.427424,76.327633,3555.0,8.176392
KRT12.4.L,4107,34.381489,3.566189,38.388839,229187.0,12.342298
MAFB.S,2516,2.639214,1.291768,62.256226,17593.0,9.775313
MSX1.L,2509,2.088959,1.127834,62.361236,13925.0,9.541512
MSX2.L,1423,0.397690,0.334821,78.652865,2651.0,7.883070
MYL1.L,2807,22.821333,3.170582,57.890789,152127.0,11.932478
MYOD1.S,2149,4.538554,1.711733,67.761776,30254.0,10.317417
NOG.L,1815,0.678218,0.517732,72.772277,4521.0,8.416710
OLIG4.L,1650,0.393639,0.331919,75.247525,2624.0,7.872836
OTX2.S,2606,1.937144,1.077438,60.906091,12913.0,9.466067
PAX3.S,1576,0.762526,0.566748,76.357636,5083.0,8.533854
PAX6.S,2295,1.537954,0.931358,65.571557,10252.0,9.235326
PAX7.L,1510,0.437294,0.362762,77.347735,2915.0,7.977968
PITX1.L,2339,6.427543,2.005195,64.911491,42846.0,10.665391
RAX.L,1474,1.754425,1.013209,77.887789,11695.0,9.367002
SIX1.L,4316,6.765077,2.049636,35.253525,45096.0,10.716571
SNAI1.S,5051,7.955446,2.192262,24.227423,53031.0,10.878651
SNAI2.L,2019,1.953195,1.082888,69.711971,13020.0,9.474319
SOX10.L,1428,2.228923,1.172149,78.577858,14858.0,9.606361
SOX17A.S,1895,2.628713,1.288878,71.572157,17523.0,9.771327
SOX2.L,2948,4.556856,1.715032,55.775578,30376.0,10.321441
SOX3.S,3283,9.227273,2.325058,50.750075,61509.0,11.026955
SOX8.L,2046,2.952445,1.374334,69.306931,19681.0,9.887460
SOX9.S,3079,2.962196,1.376798,53.810381,19746.0,9.890757
TFAP2A.L,3099,3.406841,1.483158,53.510351,22710.0,10.030604
TFAP2C.L,3594,6.421242,2.004346,46.084608,42804.0,10.664411
TP63.L,2088,1.744224,1.009499,68.676868,11627.0,9.361172
VENTX2.1.L,1717,0.399790,0.336322,74.242424,2665.0,7.888334
TBXT.S,814,0.143264,0.133888,87.788779,955.0,6.862758
ZIC1.S,2371,1.841134,1.044203,64.431443,12273.0,9.415238
OLIG3.S,1330,0.398740,0.335572,80.048005,2658.0,7.885705
EYA2.S,3957,3.455595,1.494161,40.639064,23035.0,10.044813
HOXB6.S,1510,0.629913,0.488527,77.347735,4199.0,8.342840
HOXB9.S,932,0.702670,0.532198,86.018602,4684.0,8.452121
HOXC9.S,731,0.136364,0.127833,89.033903,909.0,6.813445
HOXD11.L,1192,0.211071,0.191505,82.118212,1407.0,7.249926

In [6]:
## frequency of single transcript event (where only one transcript of a gene is detected in a cell)

from scipy.sparse import issparse

expr_matrix = adata[:, adata.var_names].X

if issparse(expr_matrix):
    expr_matrix = expr_matrix.toarray()

# create gene_by_cell expression dataFrame
gene_df = pd.DataFrame(
    expr_matrix,
    columns=adata.var_names,
    index=adata.obs_names
)


# count the frequency of single transcript event
gene_l = np.where(gene_df.to_numpy() == 1, 1,0).sum(axis=0) 

count_1 = pd.DataFrame(gene_l, 
                       index = adata.var_names,
                       columns=["number of single_transcript_event"])
count_1.to_csv(path_save + "single_transcript_event.csv")

count_1

            number of single_transcript_event
ACTC1.L                                  1296
CD44.L                                   1204
CDH1.S                                   1071
CDX4.L                                    738
CHRD.1.S                                 1092
DLX2.L                                    546
DLX3.L                                   1607
EGR2.L                                   1132
ELAVL3.L                                  836
EPHA2.L                                  1396
EPHA4.L                                  1132
EYA1.L                                   1326
FOXC2.L                                  1067
GATA2.L                                   963
GBX2.2.L                                 1160
HNF1B.L                                  1272
HOXA3.S                                  1570
HOXC10.L                                 1046
HOXD3.L                                  1035
KRT12.4.L                                1468
MAFB.S                                   1061
MSX1.L                                    895
MSX2.L                                    967
MYL1.L                                   1094
MYOD1.S                                   928
NOG.L                                    1002
OLIG4.L                                  1184
OTX2.S                                   1014
PAX3.S                                    900
PAX6.S                                   1241
PAX7.L                                   1044
PITX1.L                                  1129
RAX.L                                     804
SIX1.L                                    887
SNAI1.S                                  1158
SNAI2.L                                  1008
SOX10.L                                   740
SOX17A.S                                  763
SOX2.L                                    902
SOX3.S                                   1017
SOX8.L                                   1074
SOX9.S                                   1193
TFAP2A.L                                 1062
TFAP2C.L                                 1152
TP63.L                                    974
VENTX2.1.L                               1181
TBXT.S                                    702
ZIC1.S                                   1147
OLIG3.S                                   987
EYA2.S                                   1059
HOXB6.S                                   943
HOXB9.S                                   539
HOXC9.S                                   606
HOXD11.L                                 1019

## Evaluate the spatial specificity

In [7]:
## Evaluate the spatial specificity  by Morans'I

# normalization and log1 transform of the data
# normalization by volume
adata.obs["volume"]  
adata.obs["volume_scaled"]=adata.obs["volume"]/1000   # scaled the volume by 1000 so the normalized count will above 1
adata.obs["volume_scaled"]

if (adata.obs["volume"] <= 0).any():
    raise ValueError("Volume values must be positive and non-zero!")  # Check if volume values are valid (non-zero to avoid division by zero)
    
adata.layers["normal_volume"] = adata.layers["raw_counts_bg_removeby1"] / adata.obs["volume_scaled"].values[:, None]

## log transformation

adata.layers["log1p_normal_volume"]=adata.layers["normal_volume"].copy()
sc.pp.log1p(adata, base=2, copy=False, chunked=None, chunk_size=None, layer="log1p_normal_volume", obsm=None)

# calculate the Moran's I 

adata.X = adata.layers["log1p_normal_volume"]

sq.gr.spatial_neighbors(adata, coord_type="generic")
sq.gr.spatial_autocorr(adata, mode="moran")
adata.uns["moranI"].to_csv(path_save + "moranI.csv")

adata.uns["moranI"]

                   I     pval_norm  var_norm  pval_norm_fdr_bh
MYL1.L      0.931775  0.000000e+00  0.000047      0.000000e+00
ACTC1.L     0.924622  0.000000e+00  0.000047      0.000000e+00
MYOD1.S     0.895542  0.000000e+00  0.000047      0.000000e+00
PITX1.L     0.889972  0.000000e+00  0.000047      0.000000e+00
RAX.L       0.850988  0.000000e+00  0.000047      0.000000e+00
SOX3.S      0.848063  0.000000e+00  0.000047      0.000000e+00
SOX2.L      0.843485  0.000000e+00  0.000047      0.000000e+00
SOX10.L     0.818424  0.000000e+00  0.000047      0.000000e+00
HOXB9.S     0.785770  0.000000e+00  0.000047      0.000000e+00
SOX8.L      0.783968  0.000000e+00  0.000047      0.000000e+00
OTX2.S      0.782633  0.000000e+00  0.000047      0.000000e+00
CHRD.1.S    0.782532  0.000000e+00  0.000047      0.000000e+00
PAX6.S      0.772577  0.000000e+00  0.000047      0.000000e+00
SIX1.L      0.747669  0.000000e+00  0.000047      0.000000e+00
SOX17A.S    0.746361  0.000000e+00  0.000047      0.000000e+00
DLX2.L      0.740945  0.000000e+00  0.000047      0.000000e+00
TFAP2C.L    0.737052  0.000000e+00  0.000047      0.000000e+00
TFAP2A.L    0.726163  0.000000e+00  0.000047      0.000000e+00
ZIC1.S      0.723419  0.000000e+00  0.000047      0.000000e+00
CDH1.S      0.722421  0.000000e+00  0.000047      0.000000e+00
KRT12.4.L   0.720440  0.000000e+00  0.000047      0.000000e+00
MAFB.S      0.714052  0.000000e+00  0.000047      0.000000e+00
SNAI2.L     0.710180  0.000000e+00  0.000047      0.000000e+00
ELAVL3.L    0.684368  0.000000e+00  0.000047      0.000000e+00
CD44.L      0.679967  0.000000e+00  0.000047      0.000000e+00
EPHA4.L     0.671914  0.000000e+00  0.000047      0.000000e+00
EPHA2.L     0.671536  0.000000e+00  0.000047      0.000000e+00
MSX1.L      0.665036  0.000000e+00  0.000047      0.000000e+00
FOXC2.L     0.662895  0.000000e+00  0.000047      0.000000e+00
GATA2.L     0.655805  0.000000e+00  0.000047      0.000000e+00
SOX9.S      0.643941  0.000000e+00  0.000047      0.000000e+00
SNAI1.S     0.643569  0.000000e+00  0.000047      0.000000e+00
CDX4.L      0.632126  0.000000e+00  0.000047      0.000000e+00
EYA2.S      0.613188  0.000000e+00  0.000047      0.000000e+00
HOXD3.L     0.606007  0.000000e+00  0.000047      0.000000e+00
PAX3.S      0.600582  0.000000e+00  0.000047      0.000000e+00
DLX3.L      0.592610  0.000000e+00  0.000047      0.000000e+00
EGR2.L      0.591549  0.000000e+00  0.000047      0.000000e+00
HOXB6.S     0.560432  0.000000e+00  0.000047      0.000000e+00
HNF1B.L     0.559512  0.000000e+00  0.000047      0.000000e+00
NOG.L       0.492201  0.000000e+00  0.000047      0.000000e+00
TP63.L      0.451662  0.000000e+00  0.000047      0.000000e+00
HOXA3.S     0.391095  0.000000e+00  0.000047      0.000000e+00
GBX2.2.L    0.386304  0.000000e+00  0.000047      0.000000e+00
OLIG3.S     0.379137  0.000000e+00  0.000047      0.000000e+00
EYA1.L      0.377312  0.000000e+00  0.000047      0.000000e+00
MSX2.L      0.369245  0.000000e+00  0.000047      0.000000e+00
PAX7.L      0.346395  0.000000e+00  0.000047      0.000000e+00
OLIG4.L     0.245783  0.000000e+00  0.000047      0.000000e+00
VENTX2.1.L  0.142140  0.000000e+00  0.000047      0.000000e+00
HOXC10.L    0.138190  0.000000e+00  0.000047      0.000000e+00
TBXT.S      0.049358  2.032818e-13  0.000047      2.111004e-13
HOXC9.S     0.036547  3.796655e-08  0.000047      3.868290e-08
HOXD11.L    0.032684  7.529279e-07  0.000047      7.529279e-07

In [8]:
## draw normalized gene expression on sections

fig_save = Path(path_save + "\\spatial_expression\\")
Path(fig_save).mkdir(parents=True,exist_ok=True)
for gene in adata.var_names:
    fig, ax = plt.subplots( figsize=(12*1, 6*1) )
    sq.pl.spatial_scatter(
        adata,
        color=gene,
        cmap="gray_r",       # optional: change to 'viridis', 'plasma', etc.
        size=10,
        #return_fig=True,
        ax = ax,
        #show=False,
        shape = None,          # prevent pop-up
    )
    
    # Save to file
    plt.savefig(str(fig_save) + "\\" +  f"marker_{gene}.png", dpi=300, bbox_inches="tight")
    plt.close(fig)  # Close to save memory

WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`
WARNING: Please specify a valid `library_id` or set it permanently in `adata.uns['spatial']`